### ISSUE TITLE
Feature Request - adding subjectAltName same as commonName

### ISSUE THREAD

**Issue by kunalvshah** [ivanr/bulletproof-tls#1]
I want to dynamically generate subjectAltName. I want to use commonName as subjectAltName in the certificate. What changes I need to make in sub-ca.conf file to achieve this? 

putting subjectAltName = DNS:*.feistyduck.com, DNS:feistyduck.com is hardcoding the SAN field in the certificate.  That may not be the right thing to do if my hostname.domainname is different in the server I am signing a CSR for.

For example, CN is webserver.kunalshah.local but the Certificate Authority configuration is 
subjectAltName = DNS:*.kshah.com, DNS:kshah.com

this will produce a certificate of commonName webserver - subjectaltname - *.kshah.com - that is not what I want. I want commonName and subjectaltname both as webserver.kunalshah.local

**Comment by ivanr** [comment]
The trick is to create the configuration file on the fly, with some shell magic. Here's the command line we have in one of our exercises:

```
# openssl req -new -key server.key -out server.csr -config <(printf "[req]\ndistinguished_name = req_distinguished_name\nreq_extensions = ext\n[req_distinguished_name]\n[ext]\nsubjectAltName = DNS:www.SERVERHOSTNAME.qlued.net,DNS:SERVERHOSTNAME.qlued.net") -subj "/CN=SERVERHOSTNAME.qlued.net"
```

So, in your case, you'd create a shell script that takes possibly one hostname as input, then use a command line as above, just replacing the hardcoded names with the input variable.

IIRC, the latest version of OpenSSL (possibly not released yet), added the ability to specify SAN hosts on the command line. I haven't used it yet.
